//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitoDemoJM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Varaus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Varaus()
        {
            this.Asiakas = new HashSet<Asiakas>();
            this.Henkilokunta = new HashSet<Henkilokunta>();
            this.Hoitaja = new HashSet<Hoitaja>();
            this.Hoitopaikka = new HashSet<Hoitopaikka>();
            this.Palvelu = new HashSet<Palvelu>();
        }
    
        public int Varaus_id { get; set; }
        [Display(Name = "Palvelun Nimi")]
        public string Palvelun_Nimi { get; set; }
        public string Alku { get; set; }
        public string Loppu { get; set; }
        public Nullable<System.DateTime> pvm { get; set; }
        public Nullable<int> Type { get; set; }
        public string Huomio { get; set; }
        public Nullable<int> Hoitaja_id { get; set; }
        public Nullable<int> Hoitopaikka_id { get; set; }
        public Nullable<int> Asiakas_id { get; set; }
        public Nullable<int> Henkilokunta_id { get; set; }
        public Nullable<int> Toimipiste_id { get; set; }
        public Nullable<int> Palvelu_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakas> Asiakas { get; set; }
        public virtual Asiakas Asiakas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Henkilokunta> Henkilokunta { get; set; }
        public virtual Henkilokunta Henkilokunta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitaja> Hoitaja { get; set; }
        public virtual Hoitaja Hoitaja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitopaikka> Hoitopaikka { get; set; }
        public virtual Hoitopaikka Hoitopaikka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palvelu> Palvelu { get; set; }
        public virtual Palvelu Palvelu1 { get; set; }
        public virtual Toimipiste Toimipiste { get; set; }
    }
}
